---
- name: Verify Helm is installed
  ansible.builtin.stat:
    path: /snap/bin/helm
  register: helm_binary
  failed_when: not helm_binary.stat.exists

- name: Install Helm Diff
  kubernetes.core.helm_plugin:
    plugin_path: "https://github.com/databus23/helm-diff"
    state: present

- name: Fail with detailed message if Helm is not installed
  ansible.builtin.fail:
    msg: "Helm is not installed. Please install Helm via Snap or another method before running this playbook."
  when: not helm_binary.stat.exists

- name: Add MetalLB Helm repository
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

- name: Install MetalLB via Helm
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    namespace: "{{ homelab_namespace }}"
    create_namespace: true
    values: 
      - "--include-crds"

- name: Apply MetalLB Configuration
  kubernetes.core.k8s:
    state: present
    template:
      path: 'metallb-config.yml.j2'